//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 10:24:49 AM PDT 
//


package net.gexf._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import net.gexf._1_2draft.viz.ColorContent;
import net.gexf._1_2draft.viz.PositionContent;
import net.gexf._1_2draft.viz.SizeContent;
import net.gexf._1_2draft.viz.ThicknessContent;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.gexf._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parents_QNAME = new QName("http://www.gexf.net/1.2draft", "parents");
    private final static QName _Edge_QNAME = new QName("http://www.gexf.net/1.2draft", "edge");
    private final static QName _Keywords_QNAME = new QName("http://www.gexf.net/1.2draft", "keywords");
    private final static QName _Gexf_QNAME = new QName("http://www.gexf.net/1.2draft", "gexf");
    private final static QName _Position_QNAME = new QName("http://www.gexf.net/1.2draft", "position");
    private final static QName _Spells_QNAME = new QName("http://www.gexf.net/1.2draft", "spells");
    private final static QName _Attribute_QNAME = new QName("http://www.gexf.net/1.2draft", "attribute");
    private final static QName _Meta_QNAME = new QName("http://www.gexf.net/1.2draft", "meta");
    private final static QName _Creator_QNAME = new QName("http://www.gexf.net/1.2draft", "creator");
    private final static QName _Size_QNAME = new QName("http://www.gexf.net/1.2draft", "size");
    private final static QName _Node_QNAME = new QName("http://www.gexf.net/1.2draft", "node");
    private final static QName _Graph_QNAME = new QName("http://www.gexf.net/1.2draft", "graph");
    private final static QName _Default_QNAME = new QName("http://www.gexf.net/1.2draft", "default");
    private final static QName _Attvalues_QNAME = new QName("http://www.gexf.net/1.2draft", "attvalues");
    private final static QName _Nodes_QNAME = new QName("http://www.gexf.net/1.2draft", "nodes");
    private final static QName _Description_QNAME = new QName("http://www.gexf.net/1.2draft", "description");
    private final static QName _Edges_QNAME = new QName("http://www.gexf.net/1.2draft", "edges");
    private final static QName _Color_QNAME = new QName("http://www.gexf.net/1.2draft", "color");
    private final static QName _Attributes_QNAME = new QName("http://www.gexf.net/1.2draft", "attributes");
    private final static QName _Thickness_QNAME = new QName("http://www.gexf.net/1.2draft", "thickness");
    private final static QName _Options_QNAME = new QName("http://www.gexf.net/1.2draft", "options");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.gexf._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttvaluesContent }
     * 
     */
    public AttvaluesContent createAttvaluesContent() {
        return new AttvaluesContent();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link AttributesContent }
     * 
     */
    public AttributesContent createAttributesContent() {
        return new AttributesContent();
    }

    /**
     * Create an instance of {@link ParentsContent }
     * 
     */
    public ParentsContent createParentsContent() {
        return new ParentsContent();
    }

    /**
     * Create an instance of {@link GraphContent }
     * 
     */
    public GraphContent createGraphContent() {
        return new GraphContent();
    }

    /**
     * Create an instance of {@link EdgeContent }
     * 
     */
    public EdgeContent createEdgeContent() {
        return new EdgeContent();
    }

    /**
     * Create an instance of {@link MetaContent }
     * 
     */
    public MetaContent createMetaContent() {
        return new MetaContent();
    }

    /**
     * Create an instance of {@link EdgesContent }
     * 
     */
    public EdgesContent createEdgesContent() {
        return new EdgesContent();
    }

    /**
     * Create an instance of {@link NodesContent }
     * 
     */
    public NodesContent createNodesContent() {
        return new NodesContent();
    }

    /**
     * Create an instance of {@link Spell }
     * 
     */
    public Spell createSpell() {
        return new Spell();
    }

    /**
     * Create an instance of {@link GexfContent }
     * 
     */
    public GexfContent createGexfContent() {
        return new GexfContent();
    }

    /**
     * Create an instance of {@link AttributeContent }
     * 
     */
    public AttributeContent createAttributeContent() {
        return new AttributeContent();
    }

    /**
     * Create an instance of {@link NodeContent }
     * 
     */
    public NodeContent createNodeContent() {
        return new NodeContent();
    }

    /**
     * Create an instance of {@link Attvalue }
     * 
     */
    public Attvalue createAttvalue() {
        return new Attvalue();
    }

    /**
     * Create an instance of {@link SpellsContent }
     * 
     */
    public SpellsContent createSpellsContent() {
        return new SpellsContent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentsContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "parents")
    public JAXBElement<ParentsContent> createParents(ParentsContent value) {
        return new JAXBElement<ParentsContent>(_Parents_QNAME, ParentsContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdgeContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "edge")
    public JAXBElement<EdgeContent> createEdge(EdgeContent value) {
        return new JAXBElement<EdgeContent>(_Edge_QNAME, EdgeContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "keywords")
    public JAXBElement<String> createKeywords(String value) {
        return new JAXBElement<String>(_Keywords_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GexfContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "gexf")
    public JAXBElement<GexfContent> createGexf(GexfContent value) {
        return new JAXBElement<GexfContent>(_Gexf_QNAME, GexfContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PositionContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "position")
    public JAXBElement<PositionContent> createPosition(PositionContent value) {
        return new JAXBElement<PositionContent>(_Position_QNAME, PositionContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpellsContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "spells")
    public JAXBElement<SpellsContent> createSpells(SpellsContent value) {
        return new JAXBElement<SpellsContent>(_Spells_QNAME, SpellsContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "attribute")
    public JAXBElement<AttributeContent> createAttribute(AttributeContent value) {
        return new JAXBElement<AttributeContent>(_Attribute_QNAME, AttributeContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "meta")
    public JAXBElement<MetaContent> createMeta(MetaContent value) {
        return new JAXBElement<MetaContent>(_Meta_QNAME, MetaContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "creator")
    public JAXBElement<String> createCreator(String value) {
        return new JAXBElement<String>(_Creator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SizeContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "size")
    public JAXBElement<SizeContent> createSize(SizeContent value) {
        return new JAXBElement<SizeContent>(_Size_QNAME, SizeContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "node")
    public JAXBElement<NodeContent> createNode(NodeContent value) {
        return new JAXBElement<NodeContent>(_Node_QNAME, NodeContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "graph")
    public JAXBElement<GraphContent> createGraph(GraphContent value) {
        return new JAXBElement<GraphContent>(_Graph_QNAME, GraphContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "default")
    public JAXBElement<String> createDefault(String value) {
        return new JAXBElement<String>(_Default_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttvaluesContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "attvalues")
    public JAXBElement<AttvaluesContent> createAttvalues(AttvaluesContent value) {
        return new JAXBElement<AttvaluesContent>(_Attvalues_QNAME, AttvaluesContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodesContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "nodes")
    public JAXBElement<NodesContent> createNodes(NodesContent value) {
        return new JAXBElement<NodesContent>(_Nodes_QNAME, NodesContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EdgesContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "edges")
    public JAXBElement<EdgesContent> createEdges(EdgesContent value) {
        return new JAXBElement<EdgesContent>(_Edges_QNAME, EdgesContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColorContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "color")
    public JAXBElement<ColorContent> createColor(ColorContent value) {
        return new JAXBElement<ColorContent>(_Color_QNAME, ColorContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributesContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "attributes")
    public JAXBElement<AttributesContent> createAttributes(AttributesContent value) {
        return new JAXBElement<AttributesContent>(_Attributes_QNAME, AttributesContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThicknessContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "thickness")
    public JAXBElement<ThicknessContent> createThickness(ThicknessContent value) {
        return new JAXBElement<ThicknessContent>(_Thickness_QNAME, ThicknessContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gexf.net/1.2draft", name = "options")
    public JAXBElement<String> createOptions(String value) {
        return new JAXBElement<String>(_Options_QNAME, String.class, null, value);
    }

}
